OrdererOrgs:
  - Name: Orderer
    Domain: sad-emerald.state-space.network
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.sad-emerald.state-space.network
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.sad-emerald.state-space.network
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
